### ISSUE TITLE
compiler derived source-header dependencies

### ISSUE THREAD

**Issue by netj** [HazyResearch/sampler#18]
It'd be nice to use the compiler's `-M` flags to derive source-header dependencies and make the build fully accurate.

Currently it has to be done [manually](https://github.com/HazyResearch/sampler/blob/bc05e817bba71f4ee2359c5168616a7bc691b6bc/Makefile#L81-L83), but apparently it's missing lots of the dependencies and resulting in incorrect binaries upon incremental builds done by deepdive.

**Comment by netj** [comment]
Here's some motivation: HazyResearch/deepdive#489

**Comment by alldefector** [comment]
Good idea! (testing)
