### ISSUE TITLE
Factor function semantics inconsistency

### ISSUE THREAD

**Issue by alldefector** [HazyResearch/sampler#26]
In `factor.hxx`, the indicator functions (called `_potential_` in the code) of most factor types return either 0 or 1 given a var assignment (indicating activation), except for continuous factors (RATIO and LINEAR) and IMPLY and ONE_IS_TRUE:

1. With IMPLY, the code says `The truth table of the 'imply' function requires to return -1.0 if the body of the rule is satisfied but the head is not, and to return 0.0 if the body is not satisfied.`
2. With ONE_IS_TRUE, the code returns 1 when exactly one var is true and -1 otherwise.

I think the above "-1" cases should probably have been "0" so we have a consistent view of how inference rules are translated into factors from the user's perspective. Thoughts? @netj @chrismre 

Alternatively (or in addition), we should more systematically catalog the factor types for users (i.e., giving the user a rigorous and consistent definition of factor potentials, as a function of var values and weights).

**Comment by chrismre** [comment]
I think we should be consistent....

**Comment by syadlowsky** [comment]
+1 on user documentation here. I tried looking into this for another use, and found it hard to understand without looking carefully at the code.

**Comment by netj** [comment]
I remember @feiranwang had a good reason for -1, related to certain flavors of IMPLY factors.  Can you please elaborate on it here?

**Comment by feiranwang** [comment]
There are two versions of imply in the sampler:

1) MLN version (logical imply): returns 0 if the body is satisfied but the head is not, and return 1 if the body is not satisfied. This is the function that is "consistent".

2) the other version referred to by @alldefector. This was added because we wanted to differentiate between the body is not satisfied (p -> q, p = false, returns 0), and body is satisfied but head is not (p -> q, p = true, q = false, returns -1). This function can be used when we want to punish the latter case. This is the default imply in the current DeepDive.

**Comment by alldefector** [comment]
@feiranwang looks like the compiler is actually using `"name": "imply"` and `"id": 0` by default -- the MLN / logical imply version. So we are good there...

**Comment by alldefector** [comment]
OK, after debugging a DD application ( @xiaoling ), I now appreciate the limitation of the MLN semantic of IMPLY, and why someone wanted to deviate. Consider `is_state_abbr(i) => is_zip_code(i + 1)`, where `i` ranges over all tokens in an input doc. Typically we would care only about the cases where `is_state_abbr(i)` is true. But the MLN semantic would conflate the interesting cases like `CA 94306` and the vast majority of cases where the two tokens have nothing to do with addresses. And that vast majority (of automatic satisfaction) makes the learned rule weight always highly positive, even if it's more often not a zip code after a state abbr.

Perhaps we should change the default IMPLY indicator function to return 0 when the precedent is false:
https://github.com/HazyResearch/sampler/blob/b18de564f911ce74b8cd76e045f4edbdddec8376/src/factor.h#L193

We could call it `FUNC_IMPLY_NATURAL`. Then we can remove `FUNC_IMPLY_neg1_1` (no need for double whammy...)

**Comment by chrismre** [comment]
Please look at the VLDB15 paper :)

**Comment by alldefector** [comment]
Ah, the `Boolean Rules` paragraph on page 5 matches the `FUNC_IMPLY_neg1_1` setup. Makes sense to keep it. Not sure if we want to make all factor types switch to `{1,-1}` (per the paper) from `{0,1}`...

For now, perhaps let's just add `FUNC_IMPLY_NATURAL`? @netj Do you think it makes sense to make it the default IMPLY?

**Comment by alldefector** [comment]
@chrismre This seems to be what's going on:

1. The paper shows that the RATIO semantic with the `sign` indicator function ({1,-1}) yields the highest quality (much higher than LINEAR).
2. The current sampler code seems to be using the LINEAR semantic with the {0,1} indicator function.
3. It's easy to switch to the `sign` indicator function ({1,-1} or {1,-1,0}) in the code. Should we?
4. The [FUNC_RATIO code](https://github.com/HazyResearch/sampler/blob/fdf694a79b7fadf0443cb0581248e3066324538b/src/factor.h#L262) seems to be a way to implement the RATIO semantic by collapsing all groundings of a rule into an array of variables (which is not how grounding / variable representation works currently). @SenWu @netj @zhangce
