### ISSUE TITLE
Optimization: Categorical var weight map compression

### ISSUE THREAD

**Issue by alldefector** [HazyResearch/sampler#29]
If a factor involves categorical vars, we load the `{var assignment --> weight id}` map in the sampler to look up the weight id of a factor given an assignment. For now, we explicitly represent this lookup table in an `unordered_map`. But there are sometimes cases where we can compress this to greatly save memory and improve speed as well.

For example, if a two-var inference rule has a constant weight (i.e., not parameterized on anything), and there are 12 category values, we would be mapping up to 144 possible assignments to the same weight ID. We could detect that regularity at loading time (e.g., simply counting how many distinct weight IDs there are for a factor) and replace the `unordered_map` with a simple integer -- saving space by over 144X and time for lookups as well.

**Comment by netj** [comment]
Totally. Such ["hash consing"](https://en.wikipedia.org/wiki/Hash_consing) or "interning" indeed will be a great improvement.
