### ISSUE TITLE
learn_non_evidence flag issue

### ISSUE THREAD

**Issue by thodrek** [HazyResearch/sampler#49]
@netj @alldefector Check lines 138 - 141 in gibbs_sampler.h  For non-evidence and non-observation variables the same proposal value is assigned to both infrs.assignments_free and infrs.assignments_evid. If no other variable in a potential that this variable touches changes (e.g., single-threaded execution) then the gradient will be zero. This means that effectively learn_non_evidence does nothing. Compare with the old dimmwitted code: two separate samples are assigned to infrs.assignments_free  and infrs.assignments_evid.

**Comment by alldefector** [comment]
OK, we can fix it by generating and using a second proposal `if learn_non_evidence and !variable.is_evid`. Out curiosity, when do people usually turn on `learn_non_evidence` and what's its advantage?

**Comment by thodrek** [comment]
This can be used for maximum likelihood estimation in latent variable models. You can leverage the presence of observations
for parameter learning. To me what the sampler does during learning in that case (if you have learn_non_evidence on) is execute
something similar to the expectation-conjugate gradient algorithm which under certain conditions corresponds to EM.

New projects such as data programming could potentially benefit from that option.

On Aug 24, 2016, at 7:51 PM, alldefector <notifications@github.com<mailto:notifications@github.com>> wrote:


OK, we can fix it by generating and using a second proposal if learn_non_evidence and !variable.is<http://variable.is>_evid. Out curiosity, when do people usually turn on learn_non_evidence and what's its advantage?
