### ISSUE TITLE
Flatten sparse values of vars and sparse weights of factors

### ISSUE THREAD

**Issue by alldefector** [HazyResearch/sampler#51]
Right now we use hash tables to keep those data:
https://github.com/HazyResearch/sampler/blob/master/src/factor.h#L339-L350
https://github.com/HazyResearch/sampler/blob/master/src/variable.h#L48-L50

They are not amenable to numba / numbskull, and may be sources of substantial overhead (not quantified yet..).

We may "flatten" them in these ways:

1. For var values, we keep a flat "value of var" array similar to the "var in factor" array. At load time, we translate all the "sparse values" in var assignments and factor specs into "dense indexes". That saves us from doing the `get_domain_index` lookups in critical paths. Additional overhead is one more `vov_offset` field in `Variable`.

2. For factor weights, we repurpose `CompactFactor` from one per var-tuple to one per var-value-tuple. Before, we'd use the `factor_params` lookup table to map each `CompactFactor` object to multiple weights (with `feature_value` inconsistently in both `FactorParams` and `CompactFactor`). After, each `CompactFactor` corresponds to exactly one `feature_value` and one `weight` and there is no need for lookup. We save those lookups and can simplify the grounding process (no need for agg). Space overhead is that we'd have a lot more `CompactFactor` objects.

At a high level, these seem quite feasible. If no one sees major issues, we can make these changes in DW and then corresponding changes in numbskull. Numbskull will then have support for sparse values and sparse weights (https://github.com/HazyResearch/numbskull/issues/37).

Thoughts?

**Comment by alldefector** [comment]
Each `map` element's memory overhead is 32B (http://info.prelert.com/blog/stl-container-memory-usage), about the same as each `CompactFactor` object size. So after the change, memory footprint won't necessarily grow significantly.

**Comment by netj** [comment]
I think we should consider the overhead of extra `VariableInFactor` objects too.  For every new `CompactFactor` there should be separate `VariableInFactor` objects (as many as the factor's arity) with different `equal_to` that holds the variable's value for choosing the right weight.  I guess that way the `map`s and even the `vov_offset` may become unnecessary on the `Variable` side, but definitely more objects are needed to repeat the hyperedge structure.  Or maybe you have a more clever way to share `VIF`s somehow?

**Comment by alldefector** [comment]
No, I don't have a clever way...

Roughly it's 1 `VariableInFactor` + 1 `CompactFactor` (roughly 64B) for each edge in exchange for one `map<int64, FactorParam>` (at least 32 + 8 + 16 = 56B) plus a bunch of arithmetics and lookups. Looks like it's worth it! :)
