### ISSUE TITLE
Simplify type aliases

### ISSUE THREAD

**Issue by alldefector** [HazyResearch/sampler#52]
This is classic over-engineering.... https://github.com/HazyResearch/sampler/blob/master/src/common.h#L24-L43

**Comment by netj** [comment]
I strongly disagree.  Before this painful cleanup, every line of code was inconsistently holding the different ids and values with `long` or `int` or `double` or whatever types appeared around them.  It also became much clearer what the arrays or maps were holding, or what the i/o code was reading/writing.

**Comment by alldefector** [comment]
Ambiguous types like long vs int are just pure evil. A few typedefs are
helpful, but too many starts to overwhelm developers. Can we slim them down
to 3 types: say id, double, and short?
