### ISSUE TITLE
Not compiling on ubuntu 15.04

### ISSUE THREAD

**Issue by raphaelhoffmann** [HazyResearch/sampler#9]
On a fresh Ubuntu 15.04 (after doing sudo apt-get install g++, libnuma-dev, ..., make dep), make returns the following error:
/usr/bin/ld: src/app/gibbs/single_node_sampler.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
/lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:71: recipe for target 'dw' failed
make: *** [dw] Error 1

I noticed that you can just add -lpthread to the following line in the Makefile:
LDLIBS += -lnuma -lrt -lpthread

And then it works. Should this go into master, or are there side effects?

**Comment by netj** [comment]
I think the modification should go into master.  Not sure why it worked fine on our Linux machines / TravisCI.  Maybe -lpthread was implied by another library?
